export const queryKeys = {
  currentUser: ["auth", "me"] as const,
  heroSlides: ["hero-slides"] as const,
  categories: ["categories"] as const,
  featuredProducts: ["featured-products"] as const,
  newArrivals: ["new-arrivals"] as const,
  bestSellers: ["best-sellers"] as const,
  testimonials: ["testimonials"] as const,
  blogPosts: ["blog-posts"] as const,
  cart: ["cart"] as const,
  wishlist: ["wishlist"] as const,
  addresses: ["addresses"] as const,
  orders: ["orders"] as const,
  myReviews: ["reviews", "my"] as const,
  product: (id: string) => ["product", id] as const,
  productReviews: (id: string) => ["product-reviews", id] as const,
  products: (params: Record<string, unknown>) => ["products", params] as const,
  blogPost: (id: string) => ["blog-post", id] as const,
};
